name: Maven Run Tests when push to Main branch and newly created PRs.

on:
  # Trigger the workflow on push for the main branch
  # and pull request for main and card-* prefix branches
  push:
    branches:
      - develop
    pull_request:
      branches:
        - develop
        - # Push events to branches matching refs/heads/card-*
        - 'card-/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Test with Maven
        run: mvn -B test --file pom.xml



